services:
  app:
    image: node:18-alpine
    command: sh -c "npm install && npx prisma generate && npx prisma migrate dev --name init && npm run seed && npm run dev"
    #command: sh -c "ls /app"
    #ports:
    #  - 127.0.0.1:3000:3000
    working_dir: /app
    volumes:
      - ./:/app:Z
    environment:
      - DATABASE_URL=postgresql://root:example@db:5432/db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=db
  proxy:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:Z
    ports:
      - 8080:80 